version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smartstock-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Himal123!
      POSTGRES_DB: smartstockdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: